lav_map/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name = "pages/index.html"), name = "home"),
    path('',include('clientside.urls')),
]

lav_map/clientside/urls.py
from django.urls import path, include
from .views import *
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', pg_index),
    path('lav/<int:lav_id>/', pg_lav_page, name='lav_page'),
    path('add_rating/', pg_add_rating, name='add_rating'),
    path('lav_points/', pg_lav_points, name='lav_points'),
    path('add_form/', AddForm.as_view(redirect_authenticated_user=True), name='add_form'),
    path('edit_form/<int:lav_id>/', EditForm.as_view(redirect_authenticated_user=True), name='edit_form'),
    path('profile/', pg_profile, name='profile'),
    path('api/points/', pg_api_points),
    path('login/', MyLoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('', include('django.contrib.auth.urls')),
    path('signup/', Signup.as_view(redirect_authenticated_user=True), name = 'signup'),
    path('confirm_email/', TemplateView.as_view(template_name='registration/confirm_email.html'),
        name='confirm_email'),
    path('verify_email/<uidb64>/<token>/',
        EmailVerify.as_view(),
        name='verify_email',
        ),
    path('invalid_verify/',
        TemplateView.as_view(template_name='registration/invalid_verify.html'),
        name='invalid_verify'
        
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lav_map/clientside/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid
from PIL import Image, ExifTags
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys


def lav_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "p_%s.%s" % (uuid.uuid4().time, ext)
    return 'lav_photo/lav_{0}/{1}'.format(instance.lav_id.id, filename)

def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "u_p_%s.%s" % (uuid.uuid4().time, ext)
    return 'user_photo/user_{0}/{1}'.format(instance.id, filename)

def compressImage(uploaded_image):
    image_temp = Image.open(uploaded_image)
    outputIoStream = BytesIO()
    image_temp.thumbnail( (1280,1280) )
    try:
        image_exif = image_temp._getexif()
        image_orientation = image_exif[274]

        if image_orientation == 3:
            image_temp = image_temp.rotate(180, expand=True)
        if image_orientation == 6:
            image_temp = image_temp.rotate(-90, expand=True)
        if image_orientation == 8:
            image_temp = image_temp.rotate(90, expand=True)
    except:
        pass
    image_temp.save(outputIoStream , format='JPEG', quality=80)
    outputIoStream.seek(0)
    uploaded_image = InMemoryUploadedFile(outputIoStream,'ImageField', "%s.jpg" % uploaded_image.name.split('.')[0], 'image/jpeg', sys.getsizeof(outputIoStream), None)
    return uploaded_image

class User(AbstractUser):

    email = models.EmailField(
    ("Email"),
    unique=True,
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    photo = models.ImageField(
        verbose_name="Фото", 
        null=True,
        blank=True,
        upload_to=user_directory_path,
        default='user_photo/av.jpg'
    )
    
    name = models.CharField(
        verbose_name="Имя",
        max_length=15,
        blank=True
        )

    email_verify = models.BooleanField(
        verbose_name="Проверено",
        null=False,
        default=False
        )
    
    def save(self, *args, **kwargs):
        self.photo = compressImage(self.photo)
        super(User, self).save(*args, **kwargs)
    

class Lavochki(models.Model):
    user = models.ForeignKey(
        User, 
        on_delete = models.CASCADE, 
        verbose_name="Пользователь",
        null=False
    )

    x = models.FloatField(
        verbose_name="Долгота",
        null=False
    )

    y = models.FloatField(
        verbose_name="Широта",
        null=False
    )

    description = models.TextField(
        verbose_name="Описание", 
        null=False
    )

    is_padik =  models.BooleanField(
        verbose_name="Возле подъезда", 
        null=True,
        blank=True,
        default=None
    ) 

    is_spinka =  models.BooleanField(
        verbose_name="Спинка", 
        null=True,
        blank=True,
        default=None
    ) 

    is_ten =  models.BooleanField(
        verbose_name="В тени", 
        null=True,
        blank=True,
        default=None, 
    ) 

    date_added = models.DateTimeField(
        verbose_name="Дата добавление", 
        null=False,
        auto_now=True
    )

    is_valid = models.BooleanField(
        verbose_name="Проверено",
        null=False,
        default=False
    )

    is_edit = models.BooleanField(
        verbose_name="На редактирование",
        null=False,
        default=False
    )

class RatingStar(models.Model):
    value = models.SmallIntegerField(
        verbose_name="Звезда рейтинга",
        default=0
    )

    def __str__(self):
        return f'{self.value}'

    class Meta:
        ordering = ['-value']


class Marks(models.Model):
    user_id = models.ForeignKey(
        User, 
        on_delete = models.CASCADE, 
        verbose_name="Пользователь",
        null=False
    )

    lavochka_id = models.ForeignKey(
        Lavochki, 
        on_delete = models.CASCADE, 
        verbose_name="Лавочка",
        null=False
    )

    rating = models.ForeignKey(
        RatingStar, 
        on_delete = models.CASCADE, 
        verbose_name="Оценка",
    )

    date_added = models.DateTimeField(
        verbose_name="Дата добавления",
        null=False,
        auto_now=True
    )

class PhotoLav(models.Model):
    image_path = models.ImageField(
        verbose_name="Фото", 
        null=False,
        upload_to=lav_directory_path 
    )

    alt = models.CharField(
        verbose_name="Описание",
        null=True,
        blank=True,
        max_length=250
    )

    lav_id = models.ForeignKey(
        Lavochki, 
        on_delete = models.CASCADE, 
        verbose_name="ID лавочки",
        null=False
    )


    is_valid = models.BooleanField(
        verbose_name="Проверено", 
        null=False,
        default=False
    )

    def save(self, *args, **kwargs):
        self.image_path = compressImage(self.image_path)
        super(PhotoLav, self).save(*args, **kwargs)

lav_map/clientside/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, get_user_model
from .utils import send_email_for_verify
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.contrib.auth import authenticate, login
from django.utils.http import urlsafe_base64_decode
from django.core.exceptions import ValidationError
from django.contrib.auth.views import LoginView
from .forms import AuthenticationForm, UserCreationForm, AddLavochkaForm, AddProfileForm, AddMarksForm, AddPhotoForm
from .models import Marks, PhotoLav, Lavochki
from django.template.loader import render_to_string
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.db.models import Avg
from django.contrib import messages


# Create your views here.
User = get_user_model()

def pg_index(request):
    return render(request, "pages/index.html")

def pg_lav_points(request):
    data = {
        'objs' : Lavochki.objects.filter(is_valid=True)
    }
    return render(request, "pages/lav_points.html", data)


class AddForm(View):

    template_name = 'pages/add_form.html'
    redirect_authenticated_user = False
    redirect_post = '/add_form/'

    def get(self, request):
        context = {
            'form_lav': AddLavochkaForm(),
            'form_mark': AddMarksForm(),
            'form_photo': AddPhotoForm()
        }
        return render(request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        lav_form = AddLavochkaForm(request.POST)
        mark_form = AddMarksForm(request.POST)
        photo_form = AddPhotoForm(request.POST, request.FILES)
        user_profile = User.objects.get(pk=request.user.id)
        files = request.FILES.getlist('image_path')
        
        for name, value in kwargs.items():
            lav_obj = Lavochki.objects.get(id=value)
            lav_obj.is_edit = False
            lav_obj.save()
            mark_obj = Marks.objects.get(user_id =user_profile, lavochka_id = lav_obj)
            lav_form = AddLavochkaForm(request.POST, instance=lav_obj)
            mark_form = AddMarksForm(request.POST, instance=mark_obj)
            PhotoLav.objects.filter(lav_id=lav_obj).delete()

        if lav_form.is_valid() and mark_form.is_valid() and photo_form.is_valid() and (len(files) <= 6):
            lav_post = lav_form.save(commit=False)
            lav_post.user = user_profile
            lav_post.save()

            mark_post = mark_form.save(commit=False)
            mark_post.user_id = user_profile 
            mark_post.lavochka_id = lav_post
            mark_post.save()

            for file in files:
                photo_post = PhotoLav(
                    lav_id = lav_post,
                    image_path = file
                )
                photo_post.save()

            context = {
                'form_lav': AddLavochkaForm(),
                'form_mark': AddMarksForm(),
                'form_photo': AddPhotoForm()
            }
            messages.success(request, 'Лавочка успешно отправлена на проверку модератером.')
            return HttpResponseRedirect(self.redirect_post)
        else:
            context = {
                'form_lav': lav_form,
                'form_mark': mark_form,
                'form_photo': photo_form
            }
            messages.error(request, 'Ошибка добавление лавочки проверте форму.')
            return render(request, self.template_name, context)
    
    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and (self.request.user.is_authenticated == False):
            redirect_to = "/login/"
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a login page."
                )
            return HttpResponseRedirect(redirect_to)
        return super().dispatch(request, *args, **kwargs) 
    

class MyLoginView(LoginView):
    form_class = AuthenticationForm


class Signup(View):

    template_name = 'registration/signup.html'
    redirect_authenticated_user = False

    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = "/lav_points/"
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a login page."
                )
            return HttpResponseRedirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        context = {
            'form': UserCreationForm()
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=password)
            send_email_for_verify(request, user)
            return redirect('confirm_email')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)

class EmailVerify(View):
    
    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)

        if user is not None and token_generator.check_token(user, token):
            user.email_verify = True
            user.save()
            login(request, user)
            return redirect('/')
        return redirect('invalid_verify')

    @staticmethod
    def get_user(uidb64):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
            user = None
        return user

def pg_api_points(request):
    data = {
        "type": "FeatureCollection",
        "features": []
    }

    lavochki_obj_list = Lavochki.objects.filter(is_valid=True)
    
    for lavochka in lavochki_obj_list:

        rating = Marks.objects.filter(lavochka_id=lavochka.id).aggregate(Avg('rating'))
        photo_obj_list = PhotoLav.objects.filter(lav_id=lavochka.id).first()
        lavochka = {
            "type": "Feature",
            "id": lavochka.id,
            "geometry": {
                "type": "Point", 
                "coordinates": [lavochka.x, lavochka.y]
            }, 
            "properties": {
                "balloonContent": {'Спинка':lavochka.is_spinka, 'Тень': lavochka.is_ten, 'Падик': lavochka.is_padik},
                "balloonContentHeader": render_to_string('el/map_balloon/head.html', {'id':lavochka.id}), 
                "balloonContentBody": render_to_string('el/map_balloon/body.html', {
                    'id':lavochka.id,
                    'is_spinka':lavochka.is_spinka,
                    'is_ten':lavochka.is_ten,
                    'is_padik':lavochka.is_padik,
                    'photo_lav':photo_obj_list.image_path.url,
                    'rating':rating['rating__avg'],
                }), 
                "balloonContentFooter": render_to_string('el/map_balloon/footer.html', {'id':lavochka.id}), 
                "clusterCaption": render_to_string('el/map_balloon/caption.html', {'id':lavochka.id}), 
                "hintContent": render_to_string('el/map_balloon/hint.html', {'id':lavochka.id}),
            }
        }

        data["features"].append(lavochka)

    return JsonResponse(data)


def pg_profile(request):

    if request.user.is_authenticated:
        add_form = AddProfileForm()
        if request.method == 'POST':
            instance = User.objects.get(pk=request.user.id)
            add_form = AddProfileForm(request.POST, request.FILES, instance=instance)
            if add_form.is_valid():
                new_post = add_form.save(commit=False)
                new_post.save()
                return redirect('profile')
            else:
                return render(request, "pages/profile.html", {"form": add_form})  
        else:
            instance = User.objects.filter(pk=request.user.id).values_list('name')
            sum_lav = Lavochki.objects.filter(user=request.user.id, is_valid=True).count()
            add_form = AddProfileForm(initial={'name': instance[0][0]})
            return render(request, "pages/profile.html", {"form": add_form, "sum_lav": sum_lav})     
    else:
        return redirect('login/')


def pg_lav_page(request, lav_id):
    lav_obj = Lavochki.objects.get(id=lav_id)
    if lav_obj.is_valid:
        photo_obj = PhotoLav.objects.filter(lav_id=lav_id)
        rating = Marks.objects.filter(lavochka_id=lav_id).aggregate(Avg('rating'))['rating__avg']
        try:
            my_rating = Marks.objects.get(lavochka_id=lav_id, user_id=request.user.id).rating
        except Marks.DoesNotExist:
            my_rating = 0

        add_form = AddMarksForm()
        return render(request, "pages/lav_page.html", {"lav_obj": lav_obj, "photo_obj": photo_obj, "form": add_form, "rating": rating, "my_rating": my_rating})
    else:
        return redirect('lav_points')

       
def pg_add_rating(request):
    if request.method == 'POST':
        add_form = AddMarksForm(request.POST)
        if add_form.is_valid():
            Marks.objects.update_or_create(
                user_id = User.objects.get(pk=request.user.id),
                lavochka_id = Lavochki.objects.get(id = request.POST.get("lav_id")),
                defaults = {'rating_id': int(request.POST.get("rating"))}
            )
            lav_obj = Lavochki.objects.get(id=request.POST.get("lav_id"))

lav_map/clientside/templates/pages/add_form.html
{% extends "root.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Лавочки map{% endblock %}

{% block content %}
    {% include 'el/header.html' %}

        <div class="container g-0" id="add-form">

            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <div class="alert alert-success" role="alert">
                            {{message}} 
                        </div>
                    {% endif %}
                    {% if message.tags == 'error' %}
                        <div class="alert alert-danger" role="alert">
                            {{message}} 
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}

            {% block name %}
                <h2 class="h2-offset">Добавление лавочки</h2>
            {% endblock %}
            <div class="map_point" id="map"></div>

            <div style="padding: 0 30px 30px 30px;">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col">
                            {{ form_lav.x|as_crispy_field}}
                        </div>
                        <div class="col">
                            {{ form_lav.y|as_crispy_field }}
                        </div>
                    </div>
                    {{ form_lav.description|as_crispy_field }}
                    {{ form_lav.is_padik|as_crispy_field }}
                    {{ form_lav.is_spinka|as_crispy_field }}
                    {{ form_lav.is_ten|as_crispy_field }}

                    <div class="rating-area" style="margin-top: 10px;">
                        {% for k, v in form_mark.fields.rating.choices %}
                            <input id="rating{{v}}" type="radio" name="rating" value="{{v}}">
                            <label for="rating{{v}}"></label>
                        {% endfor %}
                    </div>
                    <br>   
                    {{ form_photo.image_path|as_crispy_field }}

                    <div class="text-end">
                        <input type="submit" class="submit-btn" value="Добавить лавочку">
                    </div>
                </form>
            </div>

            <div class="container-fluid g-0">
                <img src="{% static 'media/ndev.png' %}" class="img-fluid">   
            </div>
        </div>

    {% include 'el/footer.html' %}
{% endblock %}

{% block script %}

<script>
    var STATIC_URL = "{% static '' %}";
</script>

<script src="{% static 'js/add_form.js' %}"></script>
{% endblock %}

lav_map/clientside/templates/pages/edit_form.html
{% extends 'pages/add_form.html' %}

{% block name %}
    <h2 class="h2-offset">Редактирование лавочки</h2>
{% endblock %}

lav_map/clientside/templates/pages/index.html
{% extends "root.html" %}
{% load static %}

{% block title %}Лавочки map{% endblock %}

{% block content %}
    {% include 'el/header.html' %}

    <div class="container g-0" id="content">

        <div class="row align-items-end g-0">
            <div class="flex text-center" id="hello">
                <div class="hello-div">
                    <p id="hello1">Добро пожаловать в</p>
                    <img class="img-fluid" src="{% static 'media/logo.png' %}" width="780px" height="108px">
                    <p id="hello2">Сервис по поиску ближайших лавочек в <br> вашем городе</p>
                </div>
            </div>
            <div class="tree">
                <img style="width: 1320px;" src="{% static 'media/vdev.png' %}" class="img-fluid">   
            </div>
        </div>

        <div class="d-flex justify-content-center align-items-center" id="polos">
            <a href="/lav_points" class="reslav">Найти лавочку рядом</a>
        </div>

        <div class="flex text-center" id="descrip">
            <div class="flex text-center">
                <p class="desc">Описание</p>
                <p class="desc-text">Добро пожаловать, наш сервис поможет вам быстро и легко найти ближайшие лавочки, где вы сможете расслабиться, насладиться свежим воздухом и настроиться на позитивный лад. Просто введите своё местоположение, и мы покажем вам все ближайшие лавочки на карте. Наслаждайтесь отдыхом и приятным времяпровождением с нашим сервисом!</p>
                <a href="https://www.donationalerts.com/r/lavochkimap" class="support"><img src="{% static 'media/coin.png' %}" width="50px" id="coin">Поддержать проект</a> 
            </div>   
        </div>

    </div>

    {% include 'el/footer.html' %}
{% endblock %}

lav_map/clientside/templates/pages/lav_page.html
{% extends "root.html" %}
{% load static %}

{% block title %}Лавочки map{% endblock %}

{% block content %}
    {% include 'el/header.html' %}

    <div class="container g-0" id="content">
        <h2 class="h2-offset">Лавочка #{{lav_obj.id}}</h2>
        <div style="padding: 20px 30px 30px 30px;">
            <div class="row" id="lav-content">
                <div class="col">
                    <div id="carouselExampleIndicators" class="carousel carousel-dark slide">
                        <div class="carousel-indicators">
                            {% for ph in photo_obj %}
                            {% if forloop.counter0 == 0 %}
                                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{forloop.counter0}}" class="active" aria-current="true" aria-label="Slide 1"></button>
                                {% else %}
                                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{forloop.counter0}}" aria-label="Slide 2"></button>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="carousel-inner text-center" id="myImg">
                            {% for ph in photo_obj %}
                                {% if forloop.first %}
                                <div class="carousel-item active divimg" style="background-image: url({{ph.image_path.url}});">
                                </div>   
                                {% else %}
                                <div class="carousel-item divimg" style="background-image: url({{ph.image_path.url}});">
                                </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>

                <div class="w-100" id="space2"></div>

                <div class="col lavdesc">
                    <h2>Описание</h2>
                    <div><p>{{lav_obj.description}}</p></div>
                    Спинка: {{lav_obj.is_spinka|yesno:"Да,Нет,Неизвестно"}}
                    <br>
                    Тень: {{lav_obj.is_ten|yesno:"Да,Нет,Неизвестно"}}
                    <br>
                    Падик: {{lav_obj.is_padik|yesno:"Да,Нет,Неизвестно"}}
                    <hr>
                    Добавлено: {{lav_obj.user.username}}
                    <div id="rating-form">
                        {% include 'pages/raiting_form.html' %} 
                    </div>
                </div>
            </div>

            <div class="modal">
                <span class="close">&times;</span> 
                <div id="carouselExampleIndicators2" class="carousel slide">
                    <div class="carousel-indicators">
                        {% for ph in photo_obj %}
                        {% if forloop.counter0 == 0 %}
                            <button type="button" data-bs-target="#carouselExampleIndicators2" data-bs-slide-to="{{forloop.counter0}}" class="active" aria-current="true" aria-label="Slide 1"></button>
                            {% else %}
                            <button type="button" data-bs-target="#carouselExampleIndicators2" data-bs-slide-to="{{forloop.counter0}}" aria-label="Slide 2"></button>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="carousel-inner text-center" style="width: 90vw; height: 90vh;">
                        {% for ph in photo_obj %}
                            {% if forloop.first %}
                            <div class="carousel-item active slide3" style="background-image: url({{ph.image_path.url}});">
                            </div>   
                            {% else %}
                            <div class="carousel-item slide3" style="background-image: url({{ph.image_path.url}});">
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators2" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators2" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>

        </div>
        <div class="container-fluid g-0">
            <img src="{% static 'media/ndev.png' %}" class="img-fluid">   
        </div>

    </div>

    {% include 'el/footer.html' %}
{% endblock %}

{% block script %}

<script>
    $(function() {
        $('#myImg').click(function(){
            $('.modal').fadeToggle(100).css('display', 'flex');;
            document.getElementById("lav-content").hidden = true;
        });
        $('.close').click(function(){
            $('.modal').fadeToggle(100);
            document.getElementById("lav-content").hidden = false;
        });
    });
</script>

{% endblock %}

lav_map/clientside/templates/pages/lav_points.html
{% extends "root.html" %}
{% load static %}

{% block title %}Лавочки map{% endblock %}

{% block content %}
    {% include 'el/header.html' %}

    <div class="container g-0" id="content">
        <h2 class="h2-offset">Найти лавочку</h2>
        <div class="map_point" id="map"></div>    
        <div class="container-fluid g-0">
            <img src="{% static 'media/ndev.png' %}" class="img-fluid">   
        </div>
    </div>
    {% include 'el/footer.html' %}
{% endblock %}


{% block script %}
<script>
    var STATIC_URL = "{% static '' %}";
</script>

<script src="{% static 'js/lav_points.js' %}"></script>

{% endblock %}

lav_map/clientside/templates/pages/profile.html
{% extends "root.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Лавочки map{% endblock %}

{% block content %}
    {% include 'el/header.html' %}

    <div class="container g-0" id="content">
        <h2 class="h2-offset">Профиль</h2>

        <div id="profile">

            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="row">
                    <div class="col text-cen">
                            <div class="profile-img" style="background-image: url({{user.photo.url}});">
                                <label class="input-a" for="id_photo">Изменить фотографию</label>
                            </div>
                        {{ form.photo}}
                    </div>
                    <div class="col">
                        <h1>{{ user.username }}</h1>
                        {{ form.name|as_crispy_field }}
                        Добавлено лавочек: {{sum_lav}}
                        <br>
                        <div style="margin-top: 78px;">
                            <input type="submit" class="submit-btn" value="Сохранить">
                            <br>
                            <a href="{% url 'password_reset' %}" class="submit-a">Изменить пароль</a> 
                        </div>
                    </div>
                </div>

            </form>

        </div>

        <div class="container-fluid g-0">
            <img src="{% static 'media/ndev.png' %}" class="img-fluid">   
        </div>
    </div>

    {% include 'el/footer.html' %}
{% endblock %}

lav_map/clientside/templates/pages/raiting_form.html
{% load static %}
<form action="{% url 'add_rating' %}" method="post" enctype="multipart/form-data" name="rating-form">
    {% csrf_token %}
    <input type="hidden" value="{{lav_obj.id}}" name="lav_id">
    <div class="row align-items-center g-0">
        <div class="rating-area">
            {% for k, v in form.fields.rating.choices %}
                {% if rating >= forloop.revcounter %}
                    <input id="rating{{v}}" type="radio" name="rating" value="{{v}}">
                    <label for="rating{{v}}" class="active"></label>
                {% else %}
                    <input id="rating{{v}}" type="radio" name="rating" value="{{v}}">
                    <label for="rating{{v}}"></label>
                {% endif %}
            {% endfor %}
        </div>
        <div class="col" id="sum-rating">
            {{ rating|floatformat:1 }}
        </div>
    </div>
    <div id="my-rating">
        Моя оценка: {{ my_rating }}
    </div>
</form>

<script src="{% static 'js/raiting_form.js' %}"></script>